### ISSUE TITLE
NodeJS listen for github update?

### ISSUE THREAD

**Issue by herohamp** [Newawe/node#1]
We should have it listen for a github push then download it

**Comment by JordanB-1337** [comment]
Good idea but I disagree. The dev build should not be immediately implemented, trust me.

**Comment by herohamp** [comment]
No to the dev server I am running

**Comment by herohamp** [comment]
Sorry for my bad wording

**Comment by JordanB-1337** [comment]
dev server? where is it?

**Comment by herohamp** [comment]
dev.newawe.com its in the readme. ;P

**Comment by JordanB-1337** [comment]
i thought that was a beta

**Comment by JordanB-1337** [comment]
well anyway even if its a test server i often find i need to do stuff just after i submit. additionally we don't have real time coding so we may end up ping-pong ing with incomplete text
